site_name: python入门培训
# theme: 
theme: readthedocs
site_favicon: image/favicon.ico
repo_url: https://github.com/Viyyy/python_tutorial
nav:
  - 引言: index.md
  - 开始: start.md
  - 基础语法: basic.md
  - 心得体会: experience.md
  - 待完成: todo.md